# Numpy Deepdive

In [1]:
import numpy as np
np.random.seed(0)

In [18]:
a1 = np.random.randint(10, size = 6)
a2 = np.random.randint(100, size = (10,10))
a3 = np.random.randint(1000, size = (10,10,10))

In [19]:
print(a1)
print(a2)
print(a3)

[9 0 6 0 4 8]
[[63 67 51  8 56 91 93 87 32 19]
 [72 71 87 13 58 81 55 64 75 92]
 [36 25 32 42 14 86 28 20 82 68]
 [22 99 83  7 72 61 13  5  0  8]
 [79 79 53 11  4 39 92 45 26 74]
 [52 49 91 51 99 18 34 51 30 53]
 [58 43 55 18 45 87 65 70 53 48]
 [94 59 80 26 35 58 49 73 44 13]
 [70 38 39  8 13  7 80 22 79 89]
 [ 8 99  6 81 71 84 89 66 60 16]]
[[[ 56 882 749 663 280   4 612 305 343 542]
  [566 153 788 353 357 697 407 411  29 929]
  [371 821 631 947 854 502   7 617 137 694]
  [896 851 376 932 721 148 885 259 126 810]
  [577 532 804 324 976 112 943 650 237 360]
  [990 859 555  63 927 916 454 265 444 603]
  [623 419 339 844 274 369 842 226 225 939]
  [643 908 228 826 897 369 128 807  24 698]
  [292 355 837 134   3 226 889 680 444 417]
  [284 836  26 736 248 365 947 201 437 197]]

 [[929 647 637 606  72 246 852 135 707 213]
  [475 620 323 102 852 327 595 223 256 645]
  [347 107 926 969 979 519 149 997 476 392]
  [683 558   0 360 691 550  89  74 499 738]
  [635 343  96 851 282 718  32 115 45

In [20]:
print("The dimension of a1 ",a1.ndim )

The dimension of a1  1


In [22]:
print("The dimension of a2 ",a2.ndim )

The dimension of a2  2


In [23]:
print("The dimension of a3 ",a3.ndim )

The dimension of a3  3


In [24]:
print("The dimension of a2 ",a2.shape )

The dimension of a2  (10, 10)


In [25]:
print("The dimension of a2 ",a2.dtype )

The dimension of a2  int32


In [26]:
print("The dimension of a2 ",a2.itemsize )

The dimension of a2  4


In [27]:
print("The dimension of a2 ",a2.nbytes )

The dimension of a2  400


In [28]:
# Accessing the Numpy Array

In [29]:
a1

array([9, 0, 6, 0, 4, 8])

In [30]:
a1[0]

9

In [31]:
a1[-1]

8

In [32]:
a1[-2]

4

In [34]:
a2[2,-1]

68

In [35]:
a3[0,0,0]

56

In [36]:
# Slicing and Dicing in Numpy Arrays
# x[start:stop:step]

In [38]:
x1 = np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
x1.dtype

dtype('int32')

In [40]:
x1[:5]

array([0, 1, 2, 3, 4])

In [41]:
x1[5:]

array([5, 6, 7, 8, 9])

In [42]:
x1[::2]

array([0, 2, 4, 6, 8])

In [48]:
x2 = np.arange(100).reshape(10,10)
x2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [52]:
# Sub Arrays 
x2[0:3:1, 0:3:1]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [54]:
Subx2 =x2[:3,:3]
Subx2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [55]:
CopyofSubx2 = Subx2.copy()

In [56]:
CopyofSubx2

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [57]:
x = np.array([1,2,3])
y = np.array([10,20,30])

In [58]:
z = np.concatenate([x,y])
z

array([ 1,  2,  3, 10, 20, 30])

In [61]:
z1 = x + y
z1

array([11, 22, 33])

In [64]:
z2 = y - x
z2

array([ 9, 18, 27])

In [66]:
z3 = x*y
z3

array([10, 40, 90])

In [67]:
z4 = np.vstack([x,y])
z4

array([[ 1,  2,  3],
       [10, 20, 30]])

In [68]:
z5 = np.hstack([x,y])
z5

array([ 1,  2,  3, 10, 20, 30])

In [74]:
z6,z7 = np.split(z5,[3])
print(z6)
print(z7)

[1 2 3]
[10 20 30]
