# Introduction to Numpy

In [3]:
# Python Library for working with Numberic values as arrays
# Many functions available,  Numpy - Numeric Python
# Array object of Numpy is called ndarray

In [4]:
list = [1,2,3,4,5]

In [5]:
# in Linux environments 
!pip install numpy

You should consider upgrading via the 'c:\users\moushmi\appdata\local\programs\python\python39\python.exe -m pip install --upgrade pip' command.


In [13]:
import numpy as np

In [17]:
ar1 = np.array([1,2,3,4,5])

In [15]:
ar1

array([1, 2, 3, 4, 5])

In [16]:
type(ar1)

numpy.ndarray

In [18]:
list1 = [1,2,3,4,5]
type(list1)

list

In [19]:
np.__version__

'1.19.2'

In [20]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [21]:
a

array([0, 1, 2, 3, 4, 5])

In [22]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [24]:
# 0 Dimension
zerodim = np.array(1)
zerodim.shape

()

In [26]:
# 1 Dimension
onedim = np.array([10,20,30,40,50])
print(onedim)
print(onedim.shape)

[10 20 30 40 50]
(5,)


In [29]:
# 2 Dimension
twodim = np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(twodim)
print(twodim.shape)

[[ 10  20  30  40  50]
 [ 60  70  80  90 100]]
(2, 5)


In [30]:
# 3 Dimension
threedim = np.array([[[10,20,30],[40,50,60]],[[70,80,90],[100,200,300]]])
print(threedim)
print(threedim.shape)

[[[ 10  20  30]
  [ 40  50  60]]

 [[ 70  80  90]
  [100 200 300]]]
(2, 2, 3)


In [ ]:
# https://numpy.org/doc/stable/user/absolute_beginners.html